void InsertNode(void **top, int data, int priority);
int Displaylist(void *top);
int getListlSize(void *top);
void InsertNodeat(void **top, int data, int node_position);
void DeleteNode(void **top);
void DeleteNodeFrom(void **top, int node_position);
void Sortlist(void **top, int sorting_method);
void SearchData(void **top, int data, int searching_method);
void deletelist(void **top);
void reverse(struct node **top);
